# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
